### ISSUE TITLE
Не импортируется цвет линии из стиля QGIS

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb_mapserver#10]
При импорте стиля из QGIS для линейного объекта не импортируется цвет.
Для точек и полигонов все ок.

Вот пример стиля. 
[Границы КО 200000.qml.zip](https://github.com/nextgis/nextgisweb/files/59391/200000.qml.zip)

**Comment by dezhin** [comment]
У нас давно есть рендерер на базе QGIS и мы не планируем поддерживать конвертацию стиля из QML в Mapserver.
