### ISSUE TITLE
Error when install nextgisweb_mapserver with python 3.6.9

### ISSUE THREAD

**Issue by dotranbinh** [nextgis/nextgisweb_mapserver#14]
Hi,
I'm fact problem when install nextgisweb_mapserver with python 3.6.9

![image](https://user-images.githubusercontent.com/8316024/78891305-80ebb900-7a91-11ea-9f8a-a8e810e27667.png)

My OS version: ubuntu 18.04 
source nexgisweb_mappserver on github,  branch master 

Please support me to fix
Thanks

**Comment by dezhin** [comment]
As described in `setup.py` nextgisweb_mapserver doesn't support python 3. You can use python 2.7 which is available in Ubuntu 18.04.
